language:
  - python

python:
  - "3.6"

sudo: required

install:
  - pip install --upgrade pip
  - pip install -r requirements.txt

script:
  - cd ssmais
  - python3 manage.py makemigrations
  - python3 manage.py migrate
  # - coverage run ./manage.py test

after_success:
  - coverage
  - coverage report
